### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Gerardo-Sista** [Zaczero/Tor4NET#5]
Hello,
first of all thank you for this lib.
I wish to use your library because of ease of use. 
**CONTEXT**
I have Tor Browser installed in a folder on desktop.
I'm using VS2019 Community Edition on Win10 x64
I'm doing a WPF app targeting Framework 4.8

**MINIBUG**
in your Sample code I had to change `Tor(torDirectory, is32Bit)` with `Tor4NET.Tor(torDirectory, is32Bit)` this is a minimal problem but is quite confusing for very first useres because of "Tor is a namespace" error message by Intellisense)

**BUG?**
Your code: 
```
// Check for updates and install latest version.
if (tor.CheckForUpdates().Result)
    tor.Install().Wait();
```
throws an exception "404 not found".

Am I doing something wrong or is there some bug to fix?

Thank you

**Comment by Zaczero** [comment]
This bug has been fixed in release v1.3 *(released on NuGet & GitHub)*.
Thanks for reporting :-) 🍕
