### ISSUE TITLE
Tor Exception

### ISSUE THREAD

**Issue by Gerardo-Sista** [Zaczero/Tor4NET#6]
Hello, thanks for fixing previous bug.
I have another problem here:

**SCENARIO**
Need to download multiple contents multiple urls using Tor4Net and HTTPClient (not WebClient)

**EXCEPTION**
Tor.TorException: 'A command cannot be dispatched to a client which is no longer running'
at line
         `using (var client = tor.InitializeClient())`

**CODE**
```
                var torDirectory = System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "Tor4NET");
            
    is32Bit = !Environment.Is64BitOperatingSystem;

                var tor = new Tor4NET.Tor(torDirectory, is32Bit);

                bool needInstall = tor.CheckForUpdates().Result;

                if (needInstall)
                {
                    tor.Install().Wait(); 
                }

                using (var client = tor.InitializeClient())  // <------EXCEPTION HERE
                {
                    HttpClientHandler httpClientHandler = new HttpClientHandler() { Proxy = client.Proxy.WebProxy };

                    for (int i = 1; i <= 100; i++)
                    {
                        using (HttpClient httpClient = new HttpClient(httpClientHandler))
                        {
                            string text= await httpClient.GetStringAsync(URL);
                            Console.WriteLine(text);
                        }
                    }
                }

```

**STACKTRACE**

```
   at Tor.Controller.Command`1.Dispatch(Client client)
   at Tor.Config.Configuration.SetValue(ConfigurationNames name, Object value)
   at Tor.Config.Configuration.set_ClientUseIPv6(Boolean value)
   at Tor4NET.Tor.InitializeClient(Boolean killExistingTor)
   at OperazioneEpausa.MainWindow.<<Esegui>b__1_0>d.MoveNext() in C:\Users\Gersis\source\repos\OperazioneEpausa\OperazioneEpausa\MainWindow.xaml.cs:line 57
```

Am I missing something or is it a bug? It works no more even on first run after compile.

Thank you.

**Comment by Zaczero** [comment]
Sounds like Tor has exited before doing anything. Maybe it's AV's fault?

**Comment by Zaczero** [comment]
Does the sandbox example work fine for you?

**Comment by Gerardo-Sista** [comment]
I don't know what AV is (antivirus??) 
I did not try sandbox example... testing

**Comment by Gerardo-Sista** [comment]
Tested: your sandbox fails too:

![image](https://user-images.githubusercontent.com/34858800/87299441-508e3d80-c50c-11ea-8c60-94ba9670ac8a.png)

**Comment by Zaczero** [comment]
Try the following code snippets (one after another):

(1)
```csharp
using (var client = tor.InitializeClient(true))
```
If still does not work then move on to (2).

(2)
```csharp
using (var client = tor.InitializeClient())
{
    while (!client.IsRunning)
        Thread.Sleep(100);

    // the rest of the code
}
```

**Comment by Gerardo-Sista** [comment]
Hello,
I already tried the first and doesn't work.
The second tip is useless since code breaks before the while statement, on  tor.InitializeClient())

**Comment by Zaczero** [comment]
@Gerardo-Sista What's the output from the Tor process itself?
You can start it manually with the following command:
`tor.exe --ignore-missing-torrc --allow-missing-torrc`

It can be found inside your installation directory inside `Tor` folder.

![200714151908_cmd_de0c50](https://user-images.githubusercontent.com/10835147/87430422-7f2c1700-c5e5-11ea-906c-0ff207ce7ccb.png)

**Comment by Gerardo-Sista** [comment]
Hello, this is the output:
![image](https://user-images.githubusercontent.com/34858800/87437387-8b68a200-c5ee-11ea-9e24-bc9de8d99dcd.png)

and launching the app it gives always the same error "'A command cannot be dispatched to a client which is no longer running"

**Comment by Zaczero** [comment]
Output looks completely normal.

Windows version *(8, 8.1, 10)*?
Is it the same when you try to run the code as admin?

* Try running 32bit version of Tor *(set it in constructor)*
* Try running 64bit version of Tor *(set it in constructor)*

**Comment by Gerardo-Sista** [comment]
Ok, I investigated deeply and found your bugs.

**BUG 1**
If for some reason app is killed in an unusual way, Tor.exe keeps running and your library crashes.

**Possible solution**
You should kill any Tor.exe process  before InitializeClient().

**BUG 2**
Cannot uninstall Tor at the end of operations because Tor.exe is still running or,
also if it is not running, a nullreference exception is raised at Tor.uninstall()

![image](https://user-images.githubusercontent.com/34858800/87450152-7562dd80-c5fe-11ea-91f6-febb86e58b41.png)

**Possible solution**
I have no idea

You can reproduce these issues running the small demo app I prepared. Stop it in VS before completing  the IP list and you'll get the errors.  If you manually kill Tor.exe then everything works (except tor.uninstall).

[Tor4NetDebug.zip](https://github.com/Zaczero/Tor4NET/files/4919934/Tor4NetDebug.zip)


NOTE: I used the more recent HttpClient, Webclient is getting very old........... I suggest to update demo code.
Please let me know about your fixes.
Thank you

**Comment by Zaczero** [comment]
@Gerardo-Sista, I figured it out,
When you run Tor in 64 bit mode your app must be 64 bit as well.
Otherwise the whole IsTorRunning / KillTorProcess code is failing.

I will note that in sandbox + readme.

**Comment by Zaczero** [comment]
What's your email? I'll send u something for your time.

**Comment by Gerardo-Sista** [comment]
Is there no way to fix other than enforce App being compiled x64? This looks like a workaround....

My email however is gersis@gmail.com 
Glad to help you.
Your lib is great.

**Comment by Zaczero** [comment]
> 
> 
> Is there no way to fix other than enforce App being compiled x64? This looks like a workaround....
> 
> My email however is [gersis@gmail.com](mailto:gersis@gmail.com)
> Glad to help you.
> Your lib is great.

Just install 32 bit tor then. You have an option in the Tor constructor to select the architecture. 32 bit will work fine with your app.
